// Code generated by mockery v2.40.1. DO NOT EDIT.

package pkg_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockA is an autogenerated mock type for the A type
type MockA struct {
	mock.Mock
}

type MockA_Expecter struct {
	mock *mock.Mock
}

func (_m *MockA) EXPECT() *MockA_Expecter {
	return &MockA_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx
func (_m *MockA) Run(ctx context.Context) {
	_m.Called(ctx)
}

// MockA_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockA_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockA_Expecter) Run(ctx interface{}) *MockA_Run_Call {
	return &MockA_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockA_Run_Call) Run(run func(ctx context.Context)) *MockA_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockA_Run_Call) Return() *MockA_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockA_Run_Call) RunAndReturn(run func(context.Context)) *MockA_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockA creates a new instance of MockA. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockA(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockA {
	mock := &MockA{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
